apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::459224530222:role/eksctl-my-cluster-nodegroup-my-nod-NodeInstanceRole-JHKCXNrjva61
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

    - rolearn: arn:aws:iam::459224530222:role/codebuild
      username: codebuild
      groups:
        - system:masters
